### ISSUE TITLE
Limpar coleção de filmes em "main page"

### ISSUE THREAD

**Issue by duartefq** [duartefq/feckless-octo-turtle#15]
Filmes são apenas adicionados à coleção

**Comment by ivmelo** [comment]
No caso vc quer que os usuários possam remover filmes da lista/coleção?

**Comment by duartefq** [comment]
Nao, foi aquele erro que vc descreveu, onde os filmes ficam salvos na pilha.

**Comment by ivmelo** [comment]
Fixed.
